version: "3.5"

services:

  # PostgreSQL
  postgres:

    image: postgres:13.2

    volumes:
      - postgres-data:/var/lib/postgresql/data

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  # Gunicorn (Python)
  gunicorn:

    build:
      context: .
      dockerfile: .docker/gunicorn/Dockerfile

    volumes:
      - static-files:/var/staticfiles

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

      DJANGO_SUPERUSER_USERNAME: ${DJANGO_SUPERUSER_USERNAME}
      DJANGO_SUPERUSER_EMAIL: ${DJANGO_SUPERUSER_EMAIL}
      DJANGO_SUPERUSER_PASSWORD: ${DJANGO_SUPERUSER_PASSWORD}
      
      SECRET_KEY: ${SECRET_KEY}
      STAGE: ${STAGE}
      ROOT_URL: ${ROOT_URL}

    depends_on:
      - postgres

    expose:
      - 8000

  # Nginx (reverse-proxy)
  nginx:

    build:
      context: .
      dockerfile: .docker/nginx/Dockerfile


    volumes:
      - static-files:/var/staticfiles

    ports:
      - 80:80

    depends_on:
      - gunicorn

volumes:
  postgres-data:
  static-files:
