# Generated by Django 3.2.3 on 2021-05-20 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypeCandidature',
            fields=[
                ('code', models.CharField(max_length=1, primary_key=True, serialize=False, verbose_name='Code')),
                ('libelle', models.CharField(max_length=250, verbose_name='Libellé')),
            ],
        ),
        migrations.CreateModel(
            name='TypePlan',
            fields=[
                ('code', models.CharField(max_length=1, primary_key=True, serialize=False, verbose_name='Code')),
                ('libelle', models.CharField(max_length=250, verbose_name='Libellé')),
            ],
        ),
        migrations.CreateModel(
            name='Dispositif',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Code')),
                ('libelle', models.CharField(max_length=250, verbose_name='Libellé')),
                ('type_candidature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paf.typecandidature')),
                ('type_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paf.typeplan')),
            ],
        ),
    ]
