# Generated by Django 3.2.3 on 2021-05-21 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paf', '0002_modalite_publiccible_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(default=0, verbose_name='Code')),
                ('libelle', models.CharField(max_length=250, verbose_name='Libellé')),
                ('periode', models.CharField(max_length=250, verbose_name='Période')),
                ('duree', models.SmallIntegerField(default=0, verbose_name='Durée (heure)')),
                ('contenu', models.TextField(max_length=1000, verbose_name='Contenu')),
                ('objectifs', models.TextField(max_length=1000, verbose_name='Objectifs pédagogique')),
                ('dispositif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paf.dispositif')),
                ('modalite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paf.modalite')),
                ('public_cible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paf.publiccible')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paf.theme')),
            ],
        ),
        migrations.AddConstraint(
            model_name='module',
            constraint=models.UniqueConstraint(fields=('code', 'dispositif_id'), name='unique_id'),
        ),
    ]
