# Generated by Django 3.2.3 on 2021-05-22 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paf', '0003_auto_20210521_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('code', models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='Code')),
                ('libelle', models.CharField(max_length=250, verbose_name='Libellé')),
            ],
        ),
        migrations.CreateModel(
            name='Metier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=250, verbose_name='Libellé')),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paf.profil')),
            ],
        ),
    ]
