# Generated by Django 3.2.3 on 2021-05-31 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paf', '0006_auto_20210526_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='typecandidature',
            name='instructions',
            field=models.TextField(blank=True, max_length=1500, null=True, verbose_name='Instructions'),
        ),
    ]
