# Generated by Django 3.2.3 on 2021-06-01 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paf', '0007_typecandidature_instructions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Periode',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='Code')),
                ('libelle', models.CharField(max_length=25, verbose_name='Libellé')),
            ],
        ),
        migrations.AlterModelOptions(
            name='metier2theme',
            options={'verbose_name': 'Relation Métier/Thème'},
        ),
        migrations.AlterField(
            model_name='module',
            name='periode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paf.periode'),
        ),
    ]
