# Generated by Django 3.2.3 on 2021-06-01 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paf', '0008_auto_20210601_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periode',
            name='libelle',
            field=models.CharField(max_length=50, verbose_name='Libellé'),
        ),
    ]
